In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[2.2609e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7142, 0.2983, 0.6010],
        [0.5649, 0.3016, 0.5674],
        [0.5785, 0.3017, 0.3902],
        [0.1443, 0.1509, 0.0948],
        [0.2761, 0.8737, 0.6451]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3082, -0.1268,  0.4139],
        [-1.5006, -1.1579, -0.2103],
        [ 1.3018, -0.7451, -2.0688],
        [-0.9253,  1.7770,  0.9634],
        [ 2.1304,  0.4290,  1.3120]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.2435,  0.2152,  1.2903],
        [-1.4775, -0.2679, -0.1480],
        [ 2.1418, -0.6229, -1.6662],
        [-0.4093,  2.6107,  1.5771],
        [ 2.4856,  1.3389,  1.4848]])


Addition: syntax 2



In [10]:
print(torch.add(x, y))

tensor([[ 0.2435,  0.2152,  1.2903],
        [-1.4775, -0.2679, -0.1480],
        [ 2.1418, -0.6229, -1.6662],
        [-0.4093,  2.6107,  1.5771],
        [ 2.4856,  1.3389,  1.4848]])


Addition: providing an output tensor as argument



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.2435,  0.2152,  1.2903],
        [-1.4775, -0.2679, -0.1480],
        [ 2.1418, -0.6229, -1.6662],
        [-0.4093,  2.6107,  1.5771],
        [ 2.4856,  1.3389,  1.4848]])


Addition: in-place



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.2435,  0.2152,  1.2903],
        [-1.4775, -0.2679, -0.1480],
        [ 2.1418, -0.6229, -1.6662],
        [-0.4093,  2.6107,  1.5771],
        [ 2.4856,  1.3389,  1.4848]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [13]:
print(x[:, 1])

tensor([-0.1268, -1.1579, -0.7451,  1.7770,  0.4290])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
print(x)
print(z)

tensor([[ 0.6346, -1.2358, -0.8921, -0.8295],
        [-0.5051, -0.5946,  1.4292, -0.2571],
        [-0.5546, -2.0402,  0.6401,  0.9034],
        [-0.8234,  1.5263, -0.1558,  0.3596]])
tensor([[ 0.6346, -1.2358, -0.8921, -0.8295, -0.5051, -0.5946,  1.4292, -0.2571],
        [-0.5546, -2.0402,  0.6401,  0.9034, -0.8234,  1.5263, -0.1558,  0.3596]])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.9998])
0.9998498558998108


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [21]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    print("GPU is available")
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

GPU is available
tensor([1.9998], device='cuda:0')
tensor([1.9998], dtype=torch.float64)
